version: "3"

services:
  django-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - 8000:8000
    command: bash -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 config.asgi:application && python3 -m pip  install --no-cache-dir -r requirements.txt"
    volumes:
    - .:/code
    env_file:
      - .env
  minio:
    image: minio/minio:latest
    ports:
    - 9000:9000
    - 9001:9001
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"

  minio-client:
    image: minio/mc:latest
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host rm expo;
      /usr/bin/mc config host add --quiet --api s3v4 local http://minio:9000 minio minio123;
      /usr/bin/mc rb --force local/bucket/;
      /usr/bin/mc mb --quiet local/bucket/;
      /usr/bin/mc policy set public local/bucket;
      "
    depends_on:
      - minio